apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
      - name: bid-svc
        image: wenkaihe/bid-svc
        # imagePullPolicy: Never
        imagePullPolicy: Always
        env:
          - name: RabbitMq__Host
            value: rabbit-clusterip
          - name: RabbitMq__Username
            # value: rabbit
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: rabbitUn
          - name: RabbitMq__Password
            # value: rabbit
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: rabbitPw
          - name: ConnectionStrings__MongoDbConnection
            # value: mongodb://root:mongoPW@mongo-clusterip
            valueFrom:
              secretKeyRef:
                name: bid-secret
                key: connString
          - name: IdentityServiceUrl
            value: https://id.kemios.com
          - name: GrpcAuction
            value: http://auction-clusterip:7777
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
  - port: 80
    targetPort: 8080