# persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    # allow only one node to read and write at the same time
    - ReadWriteOnce
---
# persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    # allow only one node to read and write at the same time
    - ReadWriteOnce
---
# persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    # allow only one node to read and write at the same time
    - ReadWriteOnce