apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            # value: postgrespw
            valueFrom: 
              secretKeyRef:
                name: postgres-secret
                key: password
        ports:
        - containerPort: 5432
        volumeMounts: # for persist volume
        - mountPath: /var/data/postgres
          name: postgresdata
      volumes: # for persist volume
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-claim # name in local pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
spec:
  type: LoadBalancer
  selector:
    app: postgres # name above in deploy file
  ports:
  - port: 5432
    targetPort: 5432
