name: bid-search

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/BiddingService/**'

env:
  REGISTRY_IMAGE: wenkaihe/bid-svc
  DOCKERFILE: src/BiddingService/Dockerfile
  DEPLOYMENT_NAME: bid-svc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v3
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push the docker image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}"
        file: ${{ env.DOCKERFILE }}
        push: true
        tags: ${{ env.REGISTRY_IMAGE }}:latest
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save kemios
    - name: Restart kubernetes deployment
      run: kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}